
[[rec]]
name = "skill_rec"
save = true
owner_visible = true
schema = [
    {name = "id", data_type = "i32"},
    {name = "level", data_type = "i32"}
]

[[box]]
name = "item_tool"
box_type = "item_tool"
obj_type = "item"
save = true
owner_visible = true
