[prop]
id = {type = "String", save = true, pub = true, priv = true}
name = {type = "String", save = true, pub = true, priv = true}
x = {type = "f32", save = true, pub = true, priv = true}
y = {type = "f32", save = true, pub = true, priv = true}

[rec]

[box]
item_tool = {}