[[objects]]
name = "object"
design = "res/logic/design/obj/obj.toml"

[[objects]]
name = "role"
base = "object"
design = "res/logic/design/obj/role.toml"

[[objects]]
name = "npc"
base = "object"
design = "res/logic/design/obj/npc.toml"

[[objects]]
name = "item"
base = "object"
design = "res/logic/design/obj/item.toml"

[[containers]]
name = "container"
design = "res/logic/design/box.toml"

[[containers]]
name = "scene"
base = "box"
design = "res/logic/design/box/scene.toml"

[[containers]]
name = "item_box"
base = "box"
design = "res/logic/design/box/item_box.toml"